### ISSUE TITLE
Example issues

### ISSUE THREAD

**Issue by DerManoMann** [djairhogeuens/openapi-php#8]
``` 
   #[Schema(description: "Order Status", example: "approved", oneOf: ["placed", "approved", "delivered"])]
```
should be written using `allowableValues`

Aim is to generate this:
```yaml
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
```
